name: diagramme
description: Application Flutter pour la gestion et le suivi des projets de construction

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  lottie: ^3.3.1
  package_info_plus: ^8.0.0
  animate_do: ^4.2.0
  carousel_slider: ^5.1.1
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  share_plus: ^10.0.2
  latlong2: ^0.9.1

  flutter_screenutil: ^5.9.0
  iconsax: ^0.0.8

  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/